### ISSUE TITLE
Cmaptocamp alert manager plugin object(...)(...) fetch is not a function error

### ISSUE THREAD

**Issue by Donamarymathew** [camptocamp/grafana-prometheus-alertmanager-datasource#122]
When I config the camptocamp alertmanager plugin as a datasource, it can be successfully updated, but also get an Object(…)(…).fetch is not a function error. The same error occurs when I query from the dashboards. Does anyone know what’s going on?
By the way, the grafana version is v7.1.1 and alertmanger plugin version is v1.0.0.

**Comment by hbollon** [comment]
I doesn't achieve to reproduce your issue, do you still experiencing this with v1.1.0?

**Comment by roya** [comment]
@hbollon 
just happened to me as well after upgrading to 1.2.0.
Still have it working in other deployments with 1.0.0.
I am running grafana 8.1.2
